Added a command-line utility and a man page.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -926,8 +926,6 @@ BUILD_SAVE_TO_FILE_TRUE
 BUILD_SAVE_TO_FILE_FALSE
 BUILD_PYTHON_TRUE
 BUILD_PYTHON_FALSE
-BUILD_PPKLIB_TRUE
-BUILD_PPKLIB_FALSE
 PYTHON
 PYTHON_VERSION
 PYTHON_PREFIX
@@ -939,6 +937,10 @@ pyexecdir
 pkgpyexecdir
 PYTHON_LIBS
 PYTHON_INCS
+BUILD_UTIL_TRUE
+BUILD_UTIL_FALSE
+BUILD_PPKLIB_TRUE
+BUILD_PPKLIB_FALSE
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -952,6 +954,7 @@ enable_fast_install
 with_gnu_ld
 enable_libtool_lock
 enable_ppk_lib
+enable_util
 enable_plugins
 enable_gtk
 enable_qt
@@ -1618,6 +1621,7 @@ Optional Features:
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --disable-ppk-lib  do not build the ppasskeeper library (enabled)
+  --disable-util     do not build the command-line utility (enabled)
   --disable-plugins  do not build any plugins
   --disable-gtk      do not build the GTK plugin (autodetect)
   --disable-qt       do not build the Qt plugin  (autodetect)
@@ -6059,13 +6063,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:6062: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:6066: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:6065: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:6069: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:6068: output\"" >&5)
+  (eval echo "\"\$as_me:6072: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -7175,7 +7179,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 7178 "configure"' > conftest.$ac_ext
+  echo '#line 7182 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9590,11 +9594,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9593: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9597: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9597: \$? = $ac_status" >&5
+   echo "$as_me:9601: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9914,11 +9918,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9917: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9921: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9921: \$? = $ac_status" >&5
+   echo "$as_me:9925: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10019,11 +10023,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10022: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10026: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10026: \$? = $ac_status" >&5
+   echo "$as_me:10030: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10074,11 +10078,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10077: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10081: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10081: \$? = $ac_status" >&5
+   echo "$as_me:10085: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12866,7 +12870,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12869 "configure"
+#line 12873 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12966,7 +12970,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12969 "configure"
+#line 12973 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14977,11 +14981,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14980: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14984: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14984: \$? = $ac_status" >&5
+   echo "$as_me:14988: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15076,11 +15080,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15079: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15083: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15083: \$? = $ac_status" >&5
+   echo "$as_me:15087: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15128,11 +15132,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15131: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15135: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15135: \$? = $ac_status" >&5
+   echo "$as_me:15139: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18472,6 +18476,11 @@ if test "${enable_ppk_lib+set}" = set; then
   enableval=$enable_ppk_lib; arg_ppklib=$enableval
 fi
 
+# Check whether --enable-util was given.
+if test "${enable_util+set}" = set; then
+  enableval=$enable_util; arg_util=$enableval
+fi
+
 # Check whether --enable-plugins was given.
 if test "${enable_plugins+set}" = set; then
   enableval=$enable_plugins; arg_plugins=$enableval
@@ -18851,15 +18860,6 @@ else
   BUILD_PYTHON_FALSE=
 fi
 
-
-   if test "x$arg_ppklib" != "xno"; then
-  BUILD_PPKLIB_TRUE=
-  BUILD_PPKLIB_FALSE='#'
-else
-  BUILD_PPKLIB_TRUE='#'
-  BUILD_PPKLIB_FALSE=
-fi
-
 else
 
 
@@ -19005,7 +19005,27 @@ fi
   PYTHON_INCS=`${PYTHON}-config --includes`
 
 
+fi
 
+ if test "x$arg_util" != "xno"; then
+  BUILD_UTIL_TRUE=
+  BUILD_UTIL_FALSE='#'
+else
+  BUILD_UTIL_TRUE='#'
+  BUILD_UTIL_FALSE=
+fi
+
+
+if test "x$arg_python" = "xno" -o "x$arg_util" = "xno"; then
+   if test "x$arg_ppklib" != "xno"; then
+  BUILD_PPKLIB_TRUE=
+  BUILD_PPKLIB_FALSE='#'
+else
+  BUILD_PPKLIB_TRUE='#'
+  BUILD_PPKLIB_FALSE=
+fi
+
+else
    if true; then
   BUILD_PPKLIB_TRUE=
   BUILD_PPKLIB_FALSE='#'
@@ -19016,7 +19036,7 @@ fi
 
 fi
 
-ac_config_files="$ac_config_files Makefile src/Makefile src/gtk/Makefile src/gtk/Ask_For_Pass/Makefile src/qt/Makefile src/qt/Ask_For_Pass/Makefile src/kde/Makefile src/kde/KWallet/Makefile src/portable/Makefile src/portable/SaveToFile/Makefile src/portable/SaveToFile/encrypted/Makefile src/portable/SaveToFile/plain_text/Makefile src/ppasskeeper.pc python/Makefile"
+ac_config_files="$ac_config_files Makefile src/Makefile src/gtk/Makefile src/gtk/Ask_For_Pass/Makefile src/qt/Makefile src/qt/Ask_For_Pass/Makefile src/kde/Makefile src/kde/KWallet/Makefile src/portable/Makefile src/portable/SaveToFile/Makefile src/portable/SaveToFile/encrypted/Makefile src/portable/SaveToFile/plain_text/Makefile src/ppasskeeper.pc python/Makefile util/Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -19213,17 +19233,24 @@ $as_echo "$as_me: error: conditional \"BUILD_PYTHON\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${BUILD_PPKLIB_TRUE}" && test -z "${BUILD_PPKLIB_FALSE}"; then
-  { { $as_echo "$as_me:$LINENO: error: conditional \"BUILD_PPKLIB\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-$as_echo "$as_me: error: conditional \"BUILD_PPKLIB\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
 if test -z "${BUILD_PYTHON_TRUE}" && test -z "${BUILD_PYTHON_FALSE}"; then
   { { $as_echo "$as_me:$LINENO: error: conditional \"BUILD_PYTHON\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 $as_echo "$as_me: error: conditional \"BUILD_PYTHON\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_UTIL_TRUE}" && test -z "${BUILD_UTIL_FALSE}"; then
+  { { $as_echo "$as_me:$LINENO: error: conditional \"BUILD_UTIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+$as_echo "$as_me: error: conditional \"BUILD_UTIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_PPKLIB_TRUE}" && test -z "${BUILD_PPKLIB_FALSE}"; then
+  { { $as_echo "$as_me:$LINENO: error: conditional \"BUILD_PPKLIB\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+$as_echo "$as_me: error: conditional \"BUILD_PPKLIB\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -20102,6 +20129,7 @@ do
     "src/portable/SaveToFile/plain_text/Makefile") CONFIG_FILES="$CONFIG_FILES src/portable/SaveToFile/plain_text/Makefile" ;;
     "src/ppasskeeper.pc") CONFIG_FILES="$CONFIG_FILES src/ppasskeeper.pc" ;;
     "python/Makefile") CONFIG_FILES="$CONFIG_FILES python/Makefile" ;;
+    "util/Makefile") CONFIG_FILES="$CONFIG_FILES util/Makefile" ;;
 
   *) { { $as_echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 $as_echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
@@ -21735,7 +21763,11 @@ if test "x$arg_ppklib" = "xno"; then
   if test "x${PYTHON_FOUND}" = "xyes"; then
     echo "yes (required by the Python binding)"
   else
-    echo "no"
+    if test "x$arg_util" != "xno"; then
+      echo "yes (required by the command-line utility)"
+    else
+      echo "no"
+    fi
   fi
 else
   echo "yes"
@@ -21752,3 +21784,7 @@ echo
 echo "Bindings :"
 echo "-------------------------------------------"
 echo -n "python binding : " ; test "x${PYTHON_FOUND}" = "xno" && echo "no" || echo "yes"
+echo
+echo "Utilities :"
+echo "-------------------------------------------"
+echo -n "ppasskeeper (command-line): " ; test "x$arg_util" = "xno" && echo "no" || echo "yes"
