Added python binding Added new option to configure '--disable-plugins'

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -907,8 +907,6 @@ LIBADD_DLD_LINK
 LT_DLPREOPEN
 LIBADD_DL
 DLLIBDIR
-BUILD_PPKLIB_TRUE
-BUILD_PPKLIB_FALSE
 GTK2_FOUND_TRUE
 GTK2_FOUND_FALSE
 GTK2_CFLAGS
@@ -926,6 +924,21 @@ KDE4_FOUND_FALSE
 KDE4CONFIG
 BUILD_SAVE_TO_FILE_TRUE
 BUILD_SAVE_TO_FILE_FALSE
+BUILD_PYTHON_TRUE
+BUILD_PYTHON_FALSE
+BUILD_PPKLIB_TRUE
+BUILD_PPKLIB_FALSE
+PYTHON
+PYTHON_VERSION
+PYTHON_PREFIX
+PYTHON_EXEC_PREFIX
+PYTHON_PLATFORM
+pythondir
+pkgpythondir
+pyexecdir
+pkgpyexecdir
+PYTHON_LIBS
+PYTHON_INCS
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -939,10 +952,12 @@ enable_fast_install
 with_gnu_ld
 enable_libtool_lock
 enable_ppk_lib
+enable_plugins
 enable_gtk
 enable_qt
 enable_kde
 enable_stf
+enable_python
 '
       ac_precious_vars='build_alias
 host_alias
@@ -1603,10 +1618,12 @@ Optional Features:
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --disable-ppk-lib  do not build the ppasskeeper library (enabled)
+  --disable-plugins  do not build any plugins
   --disable-gtk      do not build the GTK plugin (autodetect)
   --disable-qt       do not build the Qt plugin  (autodetect)
   --disable-kde      do not build the KDE plugin (autodetect)
   --disable-stf      do not build the SaveToFile plugin (autodetect)
+  --disable-python   do not build the Python binding (autodetect)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -6042,13 +6059,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:6045: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:6062: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:6048: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:6065: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:6051: output\"" >&5)
+  (eval echo "\"\$as_me:6068: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -7158,7 +7175,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 7161 "configure"' > conftest.$ac_ext
+  echo '#line 7178 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9573,11 +9590,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9576: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9593: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9580: \$? = $ac_status" >&5
+   echo "$as_me:9597: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9897,11 +9914,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9900: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9917: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9904: \$? = $ac_status" >&5
+   echo "$as_me:9921: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10002,11 +10019,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10005: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10022: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10009: \$? = $ac_status" >&5
+   echo "$as_me:10026: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10057,11 +10074,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10060: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10077: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10064: \$? = $ac_status" >&5
+   echo "$as_me:10081: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12849,7 +12866,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12852 "configure"
+#line 12869 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12949,7 +12966,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12952 "configure"
+#line 12969 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14960,11 +14977,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14963: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14980: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14967: \$? = $ac_status" >&5
+   echo "$as_me:14984: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15059,11 +15076,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15062: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15079: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15066: \$? = $ac_status" >&5
+   echo "$as_me:15083: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15111,11 +15128,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15114: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15131: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15118: \$? = $ac_status" >&5
+   echo "$as_me:15135: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18455,6 +18472,11 @@ if test "${enable_ppk_lib+set}" = set; then
   enableval=$enable_ppk_lib; arg_ppklib=$enableval
 fi
 
+# Check whether --enable-plugins was given.
+if test "${enable_plugins+set}" = set; then
+  enableval=$enable_plugins; arg_plugins=$enableval
+fi
+
 # Check whether --enable-gtk was given.
 if test "${enable_gtk+set}" = set; then
   enableval=$enable_gtk; arg_gtk=$enableval
@@ -18475,6 +18497,11 @@ if test "${enable_stf+set}" = set; then
   enableval=$enable_stf; arg_stf=$enableval
 fi
 
+# Check whether --enable-python was given.
+if test "${enable_python+set}" = set; then
+  enableval=$enable_python; arg_python=$enableval
+fi
+
 
 DLLIBDIR=${libdir}/ppasskeeper
 
@@ -18484,14 +18511,12 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
- if test "x$arg_ppklib" != "xno"; then
-  BUILD_PPKLIB_TRUE=
-  BUILD_PPKLIB_FALSE='#'
-else
-  BUILD_PPKLIB_TRUE='#'
-  BUILD_PPKLIB_FALSE=
+if test "x$arg_plugins" = "xno"; then
+  arg_gtk=no
+  arg_qt=no
+  arg_kde=no
+  arg_stf=no
 fi
-
 
 if test "x$arg_gtk" = "xno"; then
    if false; then
@@ -18816,7 +18841,182 @@ else
 fi
 
 
-ac_config_files="$ac_config_files Makefile src/Makefile src/gtk/Makefile src/gtk/Ask_For_Pass/Makefile src/qt/Makefile src/qt/Ask_For_Pass/Makefile src/kde/Makefile src/kde/KWallet/Makefile src/portable/Makefile src/portable/SaveToFile/Makefile src/portable/SaveToFile/encrypted/Makefile src/portable/SaveToFile/plain_text/Makefile src/ppasskeeper.pc"
+if test "x$arg_python" = "xno"; then
+  PYTHON_FOUND="no"
+   if false; then
+  BUILD_PYTHON_TRUE=
+  BUILD_PYTHON_FALSE='#'
+else
+  BUILD_PYTHON_TRUE='#'
+  BUILD_PYTHON_FALSE=
+fi
+
+
+   if test "x$arg_ppklib" != "xno"; then
+  BUILD_PPKLIB_TRUE=
+  BUILD_PPKLIB_FALSE='#'
+else
+  BUILD_PPKLIB_TRUE='#'
+  BUILD_PPKLIB_FALSE=
+fi
+
+else
+
+
+
+
+        # Find any Python interpreter.
+    if test -z "$PYTHON"; then
+      for ac_prog in python python2 python2.5 python2.4 python2.3 python2.2 python2.1 python2.0 python1.6 python1.5
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ $as_echo "$as_me:$LINENO: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if test "${ac_cv_path_PYTHON+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+  case $PYTHON in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PYTHON="$PYTHON" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_PYTHON="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+PYTHON=$ac_cv_path_PYTHON
+if test -n "$PYTHON"; then
+  { $as_echo "$as_me:$LINENO: result: $PYTHON" >&5
+$as_echo "$PYTHON" >&6; }
+else
+  { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+  test -n "$PYTHON" && break
+done
+test -n "$PYTHON" || PYTHON=":"
+
+    fi
+    am_display_PYTHON=python
+
+
+  if test "$PYTHON" = :; then
+      PYTHON_FOUND="no"
+  else
+
+
+  { $as_echo "$as_me:$LINENO: checking for $am_display_PYTHON version" >&5
+$as_echo_n "checking for $am_display_PYTHON version... " >&6; }
+if test "${am_cv_python_version+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+  am_cv_python_version=`$PYTHON -c "import sys; print sys.version[:3]"`
+fi
+{ $as_echo "$as_me:$LINENO: result: $am_cv_python_version" >&5
+$as_echo "$am_cv_python_version" >&6; }
+  PYTHON_VERSION=$am_cv_python_version
+
+
+
+  PYTHON_PREFIX='${prefix}'
+
+  PYTHON_EXEC_PREFIX='${exec_prefix}'
+
+
+
+  { $as_echo "$as_me:$LINENO: checking for $am_display_PYTHON platform" >&5
+$as_echo_n "checking for $am_display_PYTHON platform... " >&6; }
+if test "${am_cv_python_platform+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+  am_cv_python_platform=`$PYTHON -c "import sys; print sys.platform"`
+fi
+{ $as_echo "$as_me:$LINENO: result: $am_cv_python_platform" >&5
+$as_echo "$am_cv_python_platform" >&6; }
+  PYTHON_PLATFORM=$am_cv_python_platform
+
+
+
+
+                { $as_echo "$as_me:$LINENO: checking for $am_display_PYTHON script directory" >&5
+$as_echo_n "checking for $am_display_PYTHON script directory... " >&6; }
+if test "${am_cv_python_pythondir+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+  am_cv_python_pythondir=`$PYTHON -c "from distutils import sysconfig; print sysconfig.get_python_lib(0,0,prefix='$PYTHON_PREFIX')" 2>/dev/null ||
+     echo "$PYTHON_PREFIX/lib/python$PYTHON_VERSION/site-packages"`
+fi
+{ $as_echo "$as_me:$LINENO: result: $am_cv_python_pythondir" >&5
+$as_echo "$am_cv_python_pythondir" >&6; }
+  pythondir=$am_cv_python_pythondir
+
+
+
+  pkgpythondir=\${pythondir}/$PACKAGE
+
+
+            { $as_echo "$as_me:$LINENO: checking for $am_display_PYTHON extension module directory" >&5
+$as_echo_n "checking for $am_display_PYTHON extension module directory... " >&6; }
+if test "${am_cv_python_pyexecdir+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+  am_cv_python_pyexecdir=`$PYTHON -c "from distutils import sysconfig; print sysconfig.get_python_lib(1,0,prefix='$PYTHON_EXEC_PREFIX')" 2>/dev/null ||
+     echo "${PYTHON_EXEC_PREFIX}/lib/python${PYTHON_VERSION}/site-packages"`
+fi
+{ $as_echo "$as_me:$LINENO: result: $am_cv_python_pyexecdir" >&5
+$as_echo "$am_cv_python_pyexecdir" >&6; }
+  pyexecdir=$am_cv_python_pyexecdir
+
+
+
+  pkgpyexecdir=\${pyexecdir}/$PACKAGE
+
+
+    PYTHON_FOUND="yes"
+  fi
+
+
+   if test "x${PYTHON_FOUND}" = "xyes"; then
+  BUILD_PYTHON_TRUE=
+  BUILD_PYTHON_FALSE='#'
+else
+  BUILD_PYTHON_TRUE='#'
+  BUILD_PYTHON_FALSE=
+fi
+
+  PYTHON_LIBS=`${PYTHON}-config --libs`
+  PYTHON_INCS=`${PYTHON}-config --includes`
+
+
+
+   if true; then
+  BUILD_PPKLIB_TRUE=
+  BUILD_PPKLIB_FALSE='#'
+else
+  BUILD_PPKLIB_TRUE='#'
+  BUILD_PPKLIB_FALSE=
+fi
+
+fi
+
+ac_config_files="$ac_config_files Makefile src/Makefile src/gtk/Makefile src/gtk/Ask_For_Pass/Makefile src/qt/Makefile src/qt/Ask_For_Pass/Makefile src/kde/Makefile src/kde/KWallet/Makefile src/portable/Makefile src/portable/SaveToFile/Makefile src/portable/SaveToFile/encrypted/Makefile src/portable/SaveToFile/plain_text/Makefile src/ppasskeeper.pc python/Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -18943,13 +19143,6 @@ $as_echo "$as_me: error: conditional \"am__fastdepCXX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${BUILD_PPKLIB_TRUE}" && test -z "${BUILD_PPKLIB_FALSE}"; then
-  { { $as_echo "$as_me:$LINENO: error: conditional \"BUILD_PPKLIB\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-$as_echo "$as_me: error: conditional \"BUILD_PPKLIB\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
 if test -z "${GTK2_FOUND_TRUE}" && test -z "${GTK2_FOUND_FALSE}"; then
   { { $as_echo "$as_me:$LINENO: error: conditional \"GTK2_FOUND\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -19010,6 +19203,34 @@ if test -z "${BUILD_SAVE_TO_FILE_TRUE}" && test -z "${BUILD_SAVE_TO_FILE_FALSE}"
   { { $as_echo "$as_me:$LINENO: error: conditional \"BUILD_SAVE_TO_FILE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 $as_echo "$as_me: error: conditional \"BUILD_SAVE_TO_FILE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_PYTHON_TRUE}" && test -z "${BUILD_PYTHON_FALSE}"; then
+  { { $as_echo "$as_me:$LINENO: error: conditional \"BUILD_PYTHON\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+$as_echo "$as_me: error: conditional \"BUILD_PYTHON\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_PPKLIB_TRUE}" && test -z "${BUILD_PPKLIB_FALSE}"; then
+  { { $as_echo "$as_me:$LINENO: error: conditional \"BUILD_PPKLIB\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+$as_echo "$as_me: error: conditional \"BUILD_PPKLIB\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_PYTHON_TRUE}" && test -z "${BUILD_PYTHON_FALSE}"; then
+  { { $as_echo "$as_me:$LINENO: error: conditional \"BUILD_PYTHON\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+$as_echo "$as_me: error: conditional \"BUILD_PYTHON\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_PPKLIB_TRUE}" && test -z "${BUILD_PPKLIB_FALSE}"; then
+  { { $as_echo "$as_me:$LINENO: error: conditional \"BUILD_PPKLIB\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+$as_echo "$as_me: error: conditional \"BUILD_PPKLIB\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -19880,6 +20101,7 @@ do
     "src/portable/SaveToFile/encrypted/Makefile") CONFIG_FILES="$CONFIG_FILES src/portable/SaveToFile/encrypted/Makefile" ;;
     "src/portable/SaveToFile/plain_text/Makefile") CONFIG_FILES="$CONFIG_FILES src/portable/SaveToFile/plain_text/Makefile" ;;
     "src/ppasskeeper.pc") CONFIG_FILES="$CONFIG_FILES src/ppasskeeper.pc" ;;
+    "python/Makefile") CONFIG_FILES="$CONFIG_FILES python/Makefile" ;;
 
   *) { { $as_echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 $as_echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
@@ -21508,11 +21730,25 @@ fi
 
 
 echo
-echo -n "Build the ppasskeeper library : " ; if test "x$arg_ppklib" = "xno"; then echo "no"; else echo "yes"; fi
+echo -n "Build the ppasskeeper library : "
+if test "x$arg_ppklib" = "xno"; then
+  if test "x${PYTHON_FOUND}" = "xyes"; then
+    echo "yes (required by the Python binding)"
+  else
+    echo "no"
+  fi
+else
+  echo "yes"
+fi
+
 echo
 echo "Enabled optional modules :"
 echo "-------------------------------------------"
 echo -n "gtk : " ; test -z "$GTK2_FOUND" && echo "no" || echo "$GTK2_FOUND"
 echo -n "qt  : " ; test -z "$QTGUI_FOUND" && echo "no" || echo "$QTGUI_FOUND"
 echo -n "kde : " ; test -z "$KDE4CONFIG" && echo "no" || echo "$KDE4CONFIG"
-echo -n "save_to_file : " ; if test "x$arg_stf" = "xno"; then echo "no"; else echo "yes"; fi
+echo -n "save_to_file : " ; test "x$arg_stf" = "xno" && echo "no" || echo "yes"
+echo
+echo "Bindings :"
+echo "-------------------------------------------"
+echo -n "python binding : " ; test "x${PYTHON_FOUND}" = "xno" && echo "no" || echo "yes"
